### ISSUE TITLE
8. Refactoring

### ISSUE THREAD

**Issue by smellHyang** [f-lab-edu/yanolja-clone#19]

**Comment by dayoungMM** [comment]
기능 구현에는 문제 없고, 마이너한 이슈들

- Entity에 변수명이 CamelCase 하고 SnakeCase하고 혼합되어 있습니다. CamelCase로 통일하면 좋을 것 같습니다
- Controller Return 수정: API 사용자(Front-end)가 결과값을 받아볼 수 있게 ResponseEntity의 Body에 data를 넣었으면 좋겠습니다.
- ReservationMakeDto에 Valid 조건들을 Annotation으로 달아놓으셨던데, @requestbody 옆에 @Valid 어노테이션을 달면 자동으로 유효성 검증을 해주니 추후 추가하면 좋을 것 같습니다.
